[[repos]]
repo = "builtin"
hooks = [
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/google/yamlfmt"
rev = "v0.21.0"
hooks = [
    { id = "yamlfmt" },
]

[[repos]]
repo = "https://github.com/zizmorcore/zizmor-pre-commit"
rev = "v1.29.0"
hooks = [
    { id = "zizmor" },
]
